language: nodejs

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test-only

after_success:
  - npm run docs
  - npm pack

# safelist
branches:
  only:
  - master
  - dev

# deployment
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "vandbt"
      - git config --local user.email "sharkspin@gmail.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
      branch: dev

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/**/*
    skip_cleanup: true
    on:
      tags: true